language: python
python:
  - "2.7"
  - "3.3"
  - "3.5"
 before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-pyqt5
  - sudo apt-get install -y python-pyqt5
install: "python setup.py install"
script: "python setup.py test"
